name: Déploiement
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialisation
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Installation et compilation
        run: yarn && yarn build

      - name: Déploiement
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist
